version: "3.9"

services:
  web:
    build: .
    image: agnus-app:latest
    container_name: agnus-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    # Vari√°veis de ambiente para banco externo
    environment:
      NODE_ENV: production
      PORT: 3000
    env_file:
      - .env